name: Sync Tasks, Shifts, and Events to Google Calendar

on:
  push:
    paths:
      - 'Tasks/University.md'
      - 'Tasks/Shifts.md'
      - 'Tasks/Events.md'
  schedule:
    - cron: '0 0 * * *' # 毎日午前9時 (JST)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git diff のために全履歴を取得

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Determine changed file
        id: changed_files
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            # git diff を使ってプッシュ間の変更ファイルを取得する（より堅牢な方法）
            files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
            echo "Detected changed files:"
            echo "$files"
            
            sync_paths=""
            if echo "$files" | grep -q "Tasks/University.md"; then
              sync_paths="$sync_paths Tasks/University.md"
            fi
            if echo "$files" | grep -q "Tasks/Shifts.md"; then
              sync_paths="$sync_paths Tasks/Shifts.md"
            fi
            if echo "$files" | grep -q "Tasks/Events.md"; then
              sync_paths="$sync_paths Tasks/Events.md"
            fi
            
            echo "Syncing paths: ${sync_paths# }"
            echo "file_path=${sync_paths# }" >> $GITHUB_OUTPUT
          else
            echo "Running on schedule, syncing all files."
            echo "file_path=Tasks/University.md Tasks/Shifts.md Tasks/Events.md" >> $GITHUB_OUTPUT
          fi

      - name: Run Sync Script
        if: steps.changed_files.outputs.file_path
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          for file in ${{ steps.changed_files.outputs.file_path }}; do
            python scripts/sync_to_calendar.py "$file"
          done