    name: Sync Tasks to Google Calendar

    on:
      # 毎日午前9時 (UTC) に実行
      schedule:
        - cron: '0 0 * * *' # UTC 0時 = 日本時間 午前9時

      # Tasks/University.md が変更された時にも実行
      push:
        paths:
          - 'Tasks/University.md'

    jobs:
      sync:
        runs-on: ubuntu-latest # GitHub Actionsが提供する最新のUbuntu環境を使用

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4 # リポジトリのコードをワークフローにチェックアウト

        - name: Set up Python
          uses: actions/setup-python@v5 # Python環境をセットアップ
          with:
            python-version: '3.x' # 最新のPython 3系を使用

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib # 必要なPythonライブラリをインストール

        - name: Run Google Calendar Sync Script
          env:
            # GitHub Secretsから認証情報を環境変数として渡す
            GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          run: python scripts/sync_google_calendar.py # 作成したPythonスクリプトを実行